version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sportconnect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zlAleeh1234@
      POSTGRES_DB: sportconnect
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
